import { NextResponse } from "next/server"
import { createClient } from "@/lib/supabase/server"
import { createHash } from "crypto"
import { STORAGE_FREE_TIER_BYTES } from "@/lib/portfolio/config"
import { createArtistToken, SESSION_MAX_AGE_SECONDS } from "@/lib/auth/session"

export async function POST(request: Request) {
  try {
    const body = await request.json()
    const { phone, password, artistName, studioName, address, email } = body

    if (!phone || !password || !artistName || !studioName || !address) {
      return NextResponse.json(
        { error: "Missing required fields" },
        { status: 400 }
      )
    }

    if (phone.length !== 10 || !/^\d+$/.test(phone)) {
      return NextResponse.json(
        { error: "Please enter a valid 10-digit mobile number." },
        { status: 400 }
      )
    }

    if (password.length < 6) {
      return NextResponse.json(
        { error: "Password must be at least 6 characters long." },
        { status: 400 }
      )
    }

    // Securely hash password using SHA-256 (native, zero-dependency)
    const hashedPassword = createHash("sha256").update(password).digest("hex")

    const supabase = await createClient()

    // Insert user into custom 'users' table
    const { data, error } = await supabase
      .from("users")
      .insert({
        phone,
        password: hashedPassword,
        artist_name: artistName,
        studio_name: studioName,
        address,
        email: email || null,
      })
      .select()
      .single()

    if (error) {
      if (error.code === "42P01") {
        return NextResponse.json(
          {
            error: "Database table 'users' not found. Please run the SQL schema in your Supabase SQL editor:\n\n" +
              "create table users (\n" +
              "  id bigint generated by default as identity primary key,\n" +
              "  phone varchar(15) unique not null,\n" +
              "  password varchar(64) not null,\n" +
              "  artist_name varchar(100) not null,\n" +
              "  studio_name varchar(100) not null,\n" +
              "  address varchar(255) not null,\n" +
              "  email varchar(100),\n" +
              "  created_at timestamp with time zone default timezone('utc'::text, now()) not null\n" +
              ");"
          },
          { status: 500 }
        )
      }
      
      // Postgres code 23505: Unique key violation
      if (error.code === "23505") {
        return NextResponse.json(
          { error: "An account with this phone number already exists." },
          { status: 400 }
        )
      }

      return NextResponse.json({ error: error.message }, { status: 400 })
    }

    await supabase.from("portfolio_storage_quotas").insert({
      user_id: data.id,
      free_storage_bytes: STORAGE_FREE_TIER_BYTES,
    })

    await supabase.from("portfolio_folders").insert({
      user_id: data.id,
      name: "My Portfolio",
      created_by: data.id,
    })

    // Create session object
    const sessionData = {
      id: data.id,
      phone: data.phone,
      artist_name: data.artist_name,
      studio_name: data.studio_name,
    }

    const token = createArtistToken(sessionData)
    const response = NextResponse.json({ success: true, user: sessionData, token })

    response.cookies.set("artist_session", token, {
      path: "/",
      httpOnly: true,
      secure: process.env.NODE_ENV === "production",
      sameSite: "lax",
      maxAge: SESSION_MAX_AGE_SECONDS,
    })

    return response
  } catch (err: unknown) {
    return NextResponse.json(
      { error: err instanceof Error ? err.message : "An unexpected error occurred during signup." },
      { status: 500 }
    )
  }
}
