-- Booking detail tables: payments, expenses, and expense categories

create table if not exists public.booking_payments (
  id              bigint generated by default as identity primary key,
  user_id         bigint not null references public.users(id) on delete cascade,
  booking_id      bigint not null references public.bookings(id) on delete cascade,
  payment_type    varchar(20) not null check (payment_type in ('Advance', 'Installment', 'Final Payment')),
  payment_method  varchar(20) not null check (payment_method in ('UPI', 'Cash', 'Check', 'Bank Transfer')),
  amount          numeric(12,2) not null check (amount > 0),
  payment_date    date not null,
  remark          text,
  created_at      timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at      timestamp with time zone default timezone('utc'::text, now()) not null
);

create index if not exists booking_payments_booking_id_idx on public.booking_payments(booking_id);
create index if not exists booking_payments_user_id_idx on public.booking_payments(user_id);

create table if not exists public.booking_expenses (
  id              bigint generated by default as identity primary key,
  user_id         bigint not null references public.users(id) on delete cascade,
  booking_id      bigint not null references public.bookings(id) on delete cascade,
  expense_name    varchar(200) not null,
  amount          numeric(12,2) not null check (amount > 0),
  expense_date    date not null,
  description     text,
  created_at      timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at      timestamp with time zone default timezone('utc'::text, now()) not null
);

create index if not exists booking_expenses_booking_id_idx on public.booking_expenses(booking_id);
create index if not exists booking_expenses_user_id_idx on public.booking_expenses(user_id);

create table if not exists public.booking_expense_categories (
  id              bigint generated by default as identity primary key,
  user_id         bigint not null references public.users(id) on delete cascade,
  booking_id      bigint not null references public.bookings(id) on delete cascade,
  category_name   varchar(200) not null,
  created_at      timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at      timestamp with time zone default timezone('utc'::text, now()) not null
);

create index if not exists booking_expense_categories_booking_id_idx on public.booking_expense_categories(booking_id);

drop trigger if exists booking_payments_set_updated_at on public.booking_payments;

create trigger booking_payments_set_updated_at
before update on public.booking_payments
for each row
execute function public.set_updated_at();

drop trigger if exists booking_expenses_set_updated_at on public.booking_expenses;

create trigger booking_expenses_set_updated_at
before update on public.booking_expenses
for each row
execute function public.set_updated_at();

drop trigger if exists booking_expense_categories_set_updated_at on public.booking_expense_categories;

create trigger booking_expense_categories_set_updated_at
before update on public.booking_expense_categories
for each row
execute function public.set_updated_at();
