create or replace function public.generate_inquiry_form_code()
returns text as $$
declare
  candidate text;
begin
  loop
    candidate := upper(substr(md5(random()::text || clock_timestamp()::text), 1, 10));
    exit when not exists (
      select 1 from public.users where inquiry_form_code = candidate
    );
  end loop;

  return candidate;
end;
$$ language plpgsql volatile;

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  phone varchar(15) unique not null,
  password varchar(64) not null, -- SHA-256 hashed password is exactly 64 characters
  artist_name varchar(100) not null,
  studio_name varchar(100) not null,
  address varchar(255) not null,
  email varchar(100),
  studio_logo_url text,
  is_test_user boolean default false,
  inquiry_form_code varchar(12) not null default public.generate_inquiry_form_code(),
  inquiry_form_active_until timestamp with time zone,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create unique index if not exists users_inquiry_form_code_key on public.users(inquiry_form_code);
create index if not exists users_inquiry_form_active_until_idx on public.users(inquiry_form_active_until);

create or replace function public.set_updated_at()
returns trigger as $$
begin
  new.updated_at = timezone('utc'::text, now());
  return new;
end;
$$ language plpgsql;

drop trigger if exists users_set_updated_at on public.users;

create trigger users_set_updated_at
before update on public.users
for each row
execute function public.set_updated_at();