create table if not exists public.customers (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  customer_name varchar(150) not null,
  phone varchar(20) not null,
  alt_phone varchar(20),
  email varchar(150) not null,
  address varchar(300) not null,
  reference_by varchar(150),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, phone)
);

create index if not exists customers_user_id_idx on public.customers(user_id);

drop trigger if exists customers_set_updated_at on public.customers;

create trigger customers_set_updated_at
before update on public.customers
for each row
execute function public.set_updated_at();
