create table if not exists public.bookings (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  customer_id bigint not null references public.customers(id) on delete cascade,
  booking_address varchar(300) not null,
  booking_date date not null,
  start_time time not null,
  end_time time not null,
  status varchar(20) not null check (status in ('pending', 'confirmed', 'completed', 'cancelled')),
  additional_request text,
  discount numeric(12,2) not null default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create index if not exists bookings_user_id_idx on public.bookings(user_id);
create index if not exists bookings_customer_id_idx on public.bookings(customer_id);

create table if not exists public.booking_services (
  booking_id bigint not null references public.bookings(id) on delete cascade,
  service_id bigint not null references public.services(id) on delete cascade,
  quantity int not null default 1,
  unit_price numeric(12,2) not null,
  primary key (booking_id, service_id)
);

create table if not exists public.booking_additional_charges (
  id              bigint generated by default as identity primary key,
  user_id         bigint not null references public.users(id) on delete cascade,
  booking_id      bigint not null references public.bookings(id) on delete cascade,
  charge_name     varchar(200) not null,
  quantity        int not null default 1,
  rate            numeric(12,2) not null,
  created_at      timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at      timestamp with time zone default timezone('utc'::text, now()) not null
);

create index if not exists booking_additional_charges_booking_id_idx on public.booking_additional_charges(booking_id);
create index if not exists booking_additional_charges_user_id_idx on public.booking_additional_charges(user_id);

drop trigger if exists bookings_set_updated_at on public.bookings;

create trigger bookings_set_updated_at
before update on public.bookings
for each row
execute function public.set_updated_at();

drop trigger if exists booking_additional_charges_set_updated_at on public.booking_additional_charges;

create trigger booking_additional_charges_set_updated_at
before update on public.booking_additional_charges
for each row
execute function public.set_updated_at();
