create table if not exists public.users (
  id bigint generated by default as identity primary key,
  phone varchar(15) unique not null,
  password varchar(64) not null, -- SHA-256 hashed password is exactly 64 characters
  artist_name varchar(100) not null,
  studio_name varchar(100) not null,
  address varchar(255) not null,
  email varchar(100),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create or replace function public.set_updated_at()
returns trigger as $$
begin
  new.updated_at = timezone('utc'::text, now());
  return new;
end;
$$ language plpgsql;

drop trigger if exists users_set_updated_at on public.users;

create trigger users_set_updated_at
before update on public.users
for each row
execute function public.set_updated_at();