-- Portfolio module schema for ArtistOS
-- Run after users.sql, bookings.sql

-- Extend users table
alter table users add column if not exists avatar_file_id bigint;
alter table users add column if not exists portfolio_slug varchar(100);

create unique index if not exists users_portfolio_slug_unique
  on users (portfolio_slug) where portfolio_slug is not null;

-- Folders
create table if not exists portfolio_folders (
  id bigint generated by default as identity primary key,
  uuid uuid not null default gen_random_uuid() unique,
  user_id bigint not null references users(id) on delete cascade,
  booking_id bigint references bookings(id) on delete set null,
  name varchar(255) not null,
  description text,
  is_shared boolean not null default false,
  shared_expires_at timestamptz,
  created_by bigint not null references users(id) on delete restrict,
  sort_order integer not null default 0,
  created_at timestamptz not null default timezone('utc'::text, now()),
  updated_at timestamptz not null default timezone('utc'::text, now())
);

create unique index if not exists portfolio_folders_user_booking_unique
  on portfolio_folders (user_id, booking_id) where booking_id is not null;

create unique index if not exists portfolio_folders_user_name_unique
  on portfolio_folders (user_id, lower(name));

create index if not exists portfolio_folders_user_id_idx on portfolio_folders (user_id);

drop trigger if exists portfolio_folders_set_updated_at on portfolio_folders;
create trigger portfolio_folders_set_updated_at
before update on portfolio_folders
for each row execute function public.set_updated_at();

-- Files
create table if not exists portfolio_files (
  id bigint generated by default as identity primary key,
  user_id bigint not null references users(id) on delete cascade,
  folder_id bigint not null references portfolio_folders(id) on delete cascade,
  section varchar(20),
  original_name varchar(500) not null,
  storage_path varchar(1000) not null unique,
  mime_type varchar(100) not null,
  extension varchar(10) not null,
  file_size bigint not null,
  sort_order integer not null default 0,
  uploaded_by bigint not null references users(id) on delete restrict,
  created_at timestamptz not null default timezone('utc'::text, now()),
  updated_at timestamptz not null default timezone('utc'::text, now())
);

create index if not exists portfolio_files_user_folder_idx on portfolio_files (user_id, folder_id);
create index if not exists portfolio_files_folder_section_idx on portfolio_files (folder_id, section);

drop trigger if exists portfolio_files_set_updated_at on portfolio_files;
create trigger portfolio_files_set_updated_at
before update on portfolio_files
for each row execute function public.set_updated_at();

alter table users drop constraint if exists users_avatar_file_id_fkey;
alter table users add constraint users_avatar_file_id_fkey
  foreign key (avatar_file_id) references portfolio_files(id) on delete set null;

-- Storage quotas (1:1 per user)
create table if not exists portfolio_storage_quotas (
  id bigint generated by default as identity primary key,
  user_id bigint not null unique references users(id) on delete cascade,
  free_storage_bytes bigint not null default 10000000,
  purchase_storage_bytes bigint not null default 0,
  used_storage_bytes bigint not null default 0,
  folder_view varchar(20) not null default 'largeGrid',
  file_view varchar(20) not null default 'largeGrid',
  expires_at timestamptz,
  created_at timestamptz not null default timezone('utc'::text, now()),
  updated_at timestamptz not null default timezone('utc'::text, now())
);

drop trigger if exists portfolio_storage_quotas_set_updated_at on portfolio_storage_quotas;
create trigger portfolio_storage_quotas_set_updated_at
before update on portfolio_storage_quotas
for each row execute function public.set_updated_at();

-- Storage plans catalog
create table if not exists storage_plans (
  id bigint generated by default as identity primary key,
  name varchar(100) not null,
  storage_bytes bigint not null,
  price_inr numeric(10,2) not null,
  razorpay_plan_id varchar(100) unique,
  is_active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default timezone('utc'::text, now()),
  updated_at timestamptz not null default timezone('utc'::text, now())
);

drop trigger if exists storage_plans_set_updated_at on storage_plans;
create trigger storage_plans_set_updated_at
before update on storage_plans
for each row execute function public.set_updated_at();

insert into storage_plans (name, storage_bytes, price_inr, sort_order)
select * from (values
  ('Starter — 500 MB / month', 524288000::bigint, 99.00::numeric, 1),
  ('Pro — 2 GB / month', 2147483648::bigint, 199.00::numeric, 2),
  ('Studio — 10 GB / month', 10737418240::bigint, 499.00::numeric, 3)
) as v(name, storage_bytes, price_inr, sort_order)
where not exists (select 1 from storage_plans limit 1);

-- Purchase ledger
create table if not exists portfolio_storage_purchases (
  id bigint generated by default as identity primary key,
  user_id bigint not null references users(id) on delete restrict,
  storage_bytes bigint not null,
  base_amount numeric(10,2) not null,
  gst_amount numeric(10,2) not null,
  amount numeric(10,2) not null,
  rp_order_id varchar(100),
  rp_payment_id varchar(100),
  rp_subscription_id varchar(100),
  rp_event_id varchar(100) unique,
  status varchar(20) not null default 'pending',
  payment_method varchar(50),
  quantity integer not null default 1,
  plan_id bigint references storage_plans(id),
  created_at timestamptz not null default timezone('utc'::text, now()),
  updated_at timestamptz not null default timezone('utc'::text, now())
);

create index if not exists portfolio_storage_purchases_user_idx
  on portfolio_storage_purchases (user_id);

drop trigger if exists portfolio_storage_purchases_set_updated_at on portfolio_storage_purchases;
create trigger portfolio_storage_purchases_set_updated_at
before update on portfolio_storage_purchases
for each row execute function public.set_updated_at();

-- Processed webhook events (idempotency)
create table if not exists razorpay_webhook_events (
  id bigint generated by default as identity primary key,
  event_id varchar(100) not null unique,
  event_type varchar(100) not null,
  processed_at timestamptz not null default timezone('utc'::text, now())
);
