create table if not exists public.services (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  service_name varchar(120) not null,
  duration_minutes integer not null check (duration_minutes > 0),
  price numeric(10, 2) not null check (price >= 0),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create index if not exists services_user_id_idx on public.services(user_id);

drop trigger if exists services_set_updated_at on public.services;

create trigger services_set_updated_at
before update on public.services
for each row
execute function public.set_updated_at();
