-- Create courses and academy management schema

-- 1. Courses Table
create table if not exists public.courses (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  name varchar(200) not null,
  duration varchar(100) not null,
  fee numeric(10, 2) not null check (fee >= 0),
  description text,
  batch_timing varchar(100),
  start_date date,
  max_students integer check (max_students is null or max_students > 0),
  is_active boolean not null default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create index if not exists courses_user_id_idx on public.courses(user_id);
create index if not exists courses_is_active_idx on public.courses(is_active);

-- 2. Course Services Junction (services taught in this course)
create table if not exists public.course_services (
  course_id bigint not null references public.courses(id) on delete cascade,
  service_id bigint not null references public.services(id) on delete cascade,
  primary key (course_id, service_id)
);

create index if not exists course_services_service_id_idx on public.course_services(service_id);

-- 3. Course Students (Enrollments)
create table if not exists public.course_students (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  course_id bigint not null references public.courses(id) on delete cascade,
  name varchar(150) not null,
  phone varchar(20) not null,
  address varchar(300) not null,
  email varchar(150),
  total_fee numeric(10, 2) not null check (total_fee >= 0),
  paid_fee numeric(10, 2) not null default 0 check (paid_fee >= 0),
  enrollment_date date not null default current_date,
  status varchar(20) not null default 'enrolled' check (status in ('enrolled', 'ongoing', 'completed', 'cancelled')),
  certificate_issued boolean not null default false,
  notes text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create index if not exists course_students_user_id_idx on public.course_students(user_id);
create index if not exists course_students_course_id_idx on public.course_students(course_id);
create index if not exists course_students_status_idx on public.course_students(status);

-- Enable RLS
alter table public.courses enable row level security;
alter table public.course_services enable row level security;
alter table public.course_students enable row level security;

-- Policies for courses
create policy "Users can view their own courses"
  on public.courses for select
  using (true);

create policy "Users can insert their own courses"
  on public.courses for insert
  with check (true);

create policy "Users can update their own courses"
  on public.courses for update
  using (true);

create policy "Users can delete their own courses"
  on public.courses for delete
  using (true);

-- Policies for course_services
create policy "Users can manage course services"
  on public.course_services for all
  using (true);

-- Policies for course_students
create policy "Users can view their own course students"
  on public.course_students for select
  using (true);

create policy "Users can insert their own course students"
  on public.course_students for insert
  with check (true);

create policy "Users can update their own course students"
  on public.course_students for update
  using (true);

create policy "Users can delete their own course students"
  on public.course_students for delete
  using (true);

-- Triggers for updated_at
drop trigger if exists courses_set_updated_at on public.courses;
create trigger courses_set_updated_at
before update on public.courses
for each row execute function public.set_updated_at();

drop trigger if exists course_students_set_updated_at on public.course_students;
create trigger course_students_set_updated_at
before update on public.course_students
for each row execute function public.set_updated_at();
