-- Notification queue. Producers insert rows; the dispatcher cron drains them.
--
-- A row in this table means "ready to send NOW" -- there is deliberately no
-- scheduled_for column. Producers only insert once the moment has arrived, so
-- the dispatcher's contract stays trivial: send everything still pending.

create table if not exists public.notification_events (
  id              bigint generated by default as identity primary key,
  user_id         bigint not null references public.users(id) on delete cascade,
  channel         varchar(20) not null default 'push',
  event_type      varchar(50) not null,
  entity_type     varchar(50),
  entity_id       bigint,
  title           varchar(200) not null,
  body            text not null,
  url             text,
  status          varchar(20) not null default 'pending'
                    check (status in ('pending', 'sent', 'failed', 'cancelled')),
  attempts        int not null default 0,
  devices_sent    int not null default 0,
  last_error      text,
  sent_at         timestamp with time zone,
  read_at         timestamp with time zone,
  created_at      timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at      timestamp with time zone default timezone('utc'::text, now()) not null
);

-- One event per (user, type, entity). Partial so rows without an entity --
-- test sends, future broadcasts -- never collide with each other.
create unique index if not exists notification_events_dedupe_idx
  on public.notification_events(user_id, event_type, entity_type, entity_id)
  where entity_id is not null;

-- The dispatcher's hot path: everything pending is ready to send.
create index if not exists notification_events_pending_idx
  on public.notification_events(created_at)
  where status = 'pending';

create index if not exists notification_events_user_id_idx
  on public.notification_events(user_id, created_at desc);

drop trigger if exists notification_events_set_updated_at on public.notification_events;

create trigger notification_events_set_updated_at
before update on public.notification_events
for each row
execute function public.set_updated_at();
