create table if not exists public.inquiries (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  customer_id bigint not null references public.customers(id) on delete cascade,
  booking_id bigint references public.bookings(id) on delete set null,
  booking_address varchar(300) not null,
  booking_date date not null,
  start_time time not null,
  end_time time not null,
  status varchar(20) not null default 'new' check (status in ('new', 'booked', 'cancelled')),
  additional_request text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create index if not exists inquiries_user_id_idx on public.inquiries(user_id);
create index if not exists inquiries_customer_id_idx on public.inquiries(customer_id);
create index if not exists inquiries_booking_id_idx on public.inquiries(booking_id);
create index if not exists inquiries_status_idx on public.inquiries(status);

create table if not exists public.inquiry_services (
  inquiry_id bigint not null references public.inquiries(id) on delete cascade,
  service_id bigint not null references public.services(id) on delete cascade,
  quantity int not null default 1,
  unit_price numeric(12,2) not null,
  primary key (inquiry_id, service_id)
);

drop trigger if exists inquiries_set_updated_at on public.inquiries;

create trigger inquiries_set_updated_at
before update on public.inquiries
for each row
execute function public.set_updated_at();
