create table if not exists public.user_subscriptions (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  plan_id bigint not null references public.platform_subscriptions(id),
  status varchar(20) not null default 'active',
  current_period_start timestamp with time zone default timezone('utc'::text, now()),
  current_period_end timestamp with time zone,
  next_billing_at timestamp with time zone,
  subscription_end_at timestamp with time zone,
  cancel_at_period_end boolean default false,
  rp_subscription_id varchar(255),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table if not exists public.platform_payments (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  plan_id bigint references public.platform_subscriptions(id),
  plan_name varchar(255),
  base_amount numeric not null,
  gst_amount numeric not null,
  amount numeric not null,
  status varchar(20) not null default 'pending', -- pending, completed, failed
  rp_order_id varchar(255),
  rp_subscription_id varchar(255),
  rp_payment_id varchar(255),
  rp_event_id varchar(255),
  payment_method varchar(50),
  invoice_number varchar(255),
  error_description text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.user_subscriptions enable row level security;
alter table public.platform_payments enable row level security;

-- Policies for user_subscriptions
create policy "Users can view their own subscriptions"
  on public.user_subscriptions for select
  using (true);

-- Policies for platform_payments
create policy "Users can view their own payments"
  on public.platform_payments for select
  using (true);

-- Triggers for updated_at
create trigger user_subscriptions_set_updated_at
before update on public.user_subscriptions
for each row execute function public.set_updated_at();

create trigger platform_payments_set_updated_at
before update on public.platform_payments
for each row execute function public.set_updated_at();
