-- Web Push subscriptions: one row per artist device that opted in to notifications.
-- Transport registry only -- what gets sent lives in notification_events.

create table if not exists public.push_subscriptions (
  id              bigint generated by default as identity primary key,
  user_id         bigint not null references public.users(id) on delete cascade,
  endpoint        text not null unique,
  p256dh          text not null,
  auth            text not null,
  user_agent      text,
  created_at      timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at      timestamp with time zone default timezone('utc'::text, now()) not null
);

create index if not exists push_subscriptions_user_id_idx on public.push_subscriptions(user_id);

drop trigger if exists push_subscriptions_set_updated_at on public.push_subscriptions;

create trigger push_subscriptions_set_updated_at
before update on public.push_subscriptions
for each row
execute function public.set_updated_at();
