-- Migration: Add platform_settings, support_tickets, and support_ticket_messages

-- 1. Platform Settings (Key-Value Store)
create table if not exists platform_settings (
  id bigint generated by default as identity primary key,
  key varchar(100) not null unique,
  value text,
  type varchar(20) not null default 'string', -- string, number, boolean, json
  description text,
  updated_at timestamptz not null default timezone('utc'::text, now())
);

drop trigger if exists platform_settings_set_updated_at on platform_settings;
create trigger platform_settings_set_updated_at
before update on platform_settings
for each row execute function public.set_updated_at();

-- Insert default values (e.g. GST Rate)
insert into platform_settings (key, value, type, description)
values 
  ('maintenance_mode', 'false', 'boolean', 'If true, the application is in maintenance mode'),
  ('global_gst_rate', '0.18', 'number', 'Global GST rate applied to purchases (e.g. 0.18 for 18%)')
on conflict (key) do nothing;

-- 2. Support Tickets
create table if not exists support_tickets (
  id bigint generated by default as identity primary key,
  user_id bigint not null references users(id) on delete cascade,
  subject varchar(255) not null,
  status varchar(20) not null default 'open', -- open, in_progress, resolved, closed
  priority varchar(20) not null default 'normal', -- low, normal, high, urgent
  created_at timestamptz not null default timezone('utc'::text, now()),
  updated_at timestamptz not null default timezone('utc'::text, now())
);

create index if not exists support_tickets_user_id_idx on support_tickets (user_id);
create index if not exists support_tickets_status_idx on support_tickets (status);

drop trigger if exists support_tickets_set_updated_at on support_tickets;
create trigger support_tickets_set_updated_at
before update on support_tickets
for each row execute function public.set_updated_at();


-- 3. Support Ticket Messages
create table if not exists support_ticket_messages (
  id bigint generated by default as identity primary key,
  ticket_id bigint not null references support_tickets(id) on delete cascade,
  sender_type varchar(20) not null, -- 'user' or 'admin'
  sender_id bigint references users(id) on delete set null, -- Optional if admin replies (could be null for system admin)
  message text not null,
  created_at timestamptz not null default timezone('utc'::text, now())
);

create index if not exists support_ticket_messages_ticket_id_idx on support_ticket_messages (ticket_id);
