-- Drop old automated WhatsApp tables
DROP TABLE IF EXISTS public.whatsapp_devices;
DROP TABLE IF EXISTS public.broadcast_messages;
DROP TABLE IF EXISTS public.broadcast_campaigns;

-- Create whatsapp_templates table
CREATE TABLE IF NOT EXISTS public.whatsapp_templates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES public.users(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    image_url TEXT,
    language TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Add RLS policies for whatsapp_templates
ALTER TABLE public.whatsapp_templates ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view their own templates and system templates" 
    ON public.whatsapp_templates FOR SELECT 
    USING (true); -- Custom auth handled by application

CREATE POLICY "Users can insert their own templates" 
    ON public.whatsapp_templates FOR INSERT 
    WITH CHECK (true); -- Custom auth handled by application

CREATE POLICY "Users can update their own templates" 
    ON public.whatsapp_templates FOR UPDATE 
    USING (true); -- Custom auth handled by application

CREATE POLICY "Users can delete their own templates" 
    ON public.whatsapp_templates FOR DELETE 
    USING (true); -- Custom auth handled by application

-- Insert some default templates (system templates where user_id is null)
INSERT INTO public.whatsapp_templates (title, content) VALUES
('Summer Sale ☀️', 'Hi {{name}}! ☀️\n\n{We''re running|Check out} our exclusive Summer Sale! Get {20%|25%|30%} off all {bookings|services} if you book this week. 🏖️\n\n{Reply|Message us} to claim your discount!'),
('Reminder / Follow-up 📅', '{Hey|Hi} {{name}} 👋\n\nJust reaching out to see if you''re still interested in booking a session with us. 🗓️ Let me know if you have any questions!\n\nBest, ArtistOS'),
('New Service Alert 🚀', 'Exciting news, {{name}}! 🎉\n\nWe just launched a brand new {service|offering} that you might love. ✨ Check our portfolio and {book now|let us know} if you want to try it out!'),
('Thank You 💖', '{Hi|Hello} {{name}}! 💖\n\nJust wanted to send a quick {note|message} to say thank you for being a wonderful {client|customer}. We truly appreciate your support! 🙏'),
('Holiday Greetings 🎄', 'Happy Holidays, {{name}}! 🎄✨\n\nWishing you and your loved ones a {joyful|wonderful} season. Stay safe and {see you soon|talk to you soon}! 🎁');
