-- Create table for storing WhatsApp OTPs
create table if not exists public.whatsapp_otps (
  id bigint generated by default as identity primary key,
  phone varchar(15) not null unique,
  otp_hash varchar(64) not null,
  expires_at timestamp with time zone not null,
  verified boolean default false not null,
  attempts integer default 0 not null,
  send_count integer default 1 not null,
  locked_until timestamp with time zone default null,
  last_sent_at timestamp with time zone default timezone('utc'::text, now()) not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create index if not exists whatsapp_otps_phone_idx on public.whatsapp_otps(phone);
create index if not exists whatsapp_otps_created_at_idx on public.whatsapp_otps(created_at desc);

-- Make password nullable for OTP-authenticated accounts
alter table if exists public.users alter column password drop not null;
