-- Create whatsapp_devices table
CREATE TABLE IF NOT EXISTS public.whatsapp_devices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    session_status TEXT NOT NULL DEFAULT 'DISCONNECTED',
    session_data JSONB,
    last_connected_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create broadcast_campaigns table
CREATE TABLE IF NOT EXISTS public.broadcast_campaigns (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    message_template TEXT NOT NULL,
    image_url TEXT,
    status TEXT NOT NULL DEFAULT 'DRAFT',
    min_delay_sec INTEGER NOT NULL DEFAULT 240,
    max_delay_sec INTEGER NOT NULL DEFAULT 300,
    business_hours_only BOOLEAN NOT NULL DEFAULT false,
    scheduled_for TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create broadcast_messages table
CREATE TABLE IF NOT EXISTS public.broadcast_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campaign_id BIGINT NOT NULL REFERENCES public.broadcast_campaigns(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    customer_id BIGINT REFERENCES public.customers(id) ON DELETE SET NULL,
    phone_number TEXT NOT NULL,
    formatted_message TEXT,
    status TEXT NOT NULL DEFAULT 'PENDING',
    error_message TEXT,
    sent_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Add RLS policies for whatsapp_devices
ALTER TABLE public.whatsapp_devices ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view their own devices" ON public.whatsapp_devices FOR SELECT USING (true);
CREATE POLICY "Users can insert their own devices" ON public.whatsapp_devices FOR INSERT WITH CHECK (true);
CREATE POLICY "Users can update their own devices" ON public.whatsapp_devices FOR UPDATE USING (true);
CREATE POLICY "Users can delete their own devices" ON public.whatsapp_devices FOR DELETE USING (true);

-- Add RLS policies for broadcast_campaigns
ALTER TABLE public.broadcast_campaigns ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view their own campaigns" ON public.broadcast_campaigns FOR SELECT USING (true);
CREATE POLICY "Users can insert their own campaigns" ON public.broadcast_campaigns FOR INSERT WITH CHECK (true);
CREATE POLICY "Users can update their own campaigns" ON public.broadcast_campaigns FOR UPDATE USING (true);
CREATE POLICY "Users can delete their own campaigns" ON public.broadcast_campaigns FOR DELETE USING (true);

-- Add RLS policies for broadcast_messages
ALTER TABLE public.broadcast_messages ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view their own messages" ON public.broadcast_messages FOR SELECT USING (true);
CREATE POLICY "Users can insert their own messages" ON public.broadcast_messages FOR INSERT WITH CHECK (true);
CREATE POLICY "Users can update their own messages" ON public.broadcast_messages FOR UPDATE USING (true);
CREATE POLICY "Users can delete their own messages" ON public.broadcast_messages FOR DELETE USING (true);

-- I'm simplifying RLS policies with "true" because custom auth logic is handled on the Next.js API route layer using session data.
-- (The existing tables seem to have custom auth, so complex RLS based on auth.uid() won't work since user_id is linked to public.users, not auth.users)
